2025-07-03 18:21:24,369 - INFO - Added book: Test Book (ID: 123)
2025-07-03 18:24:05,521 - INFO - Added book: Test Book (ID: 123)
2025-07-03 18:24:10,371 - INFO - Added book: Test Book (ID: 123)
2025-07-03 18:26:00,475 - INFO - Added book: Test Book (ID: 123)
2025-07-03 18:30:26,453 - INFO - Added book: Test Book (ID: 123)
2025-07-03 18:30:36,408 - INFO - Added book: Test Book (ID: 123)
2025-07-03 18:30:37,479 - INFO - ==================================================
2025-07-03 18:30:37,479 - INFO - Start environment debugging information:
2025-07-03 18:30:37,479 - INFO - current working directory: d:\OneDrive\桌面\111111
2025-07-03 18:30:37,479 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\111111', 'd:\\OneDrive\\桌面\\111111\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\111111', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\111111\\src']
2025-07-03 18:30:37,490 - INFO - RecommendationService Loading successful
2025-07-03 18:30:37,490 - INFO - reset_books exist: True
2025-07-03 18:30:37,490 - INFO - ==================================================
2025-07-03 18:30:37,490 - INFO - Successfully imported LibraryApp
2025-07-03 18:30:37,490 - INFO - LibraryApp Instance created successfully
2025-07-03 18:30:37,490 - INFO - The method to display the login interface has been called
2025-07-03 18:39:00,998 - INFO - Added book: Test Book (ID: 123)
2025-07-03 19:00:25,781 - INFO - ==================================================
2025-07-03 19:00:25,781 - INFO - Start environment debugging information:
2025-07-03 19:00:25,781 - INFO - current working directory: d:\OneDrive\桌面\111111
2025-07-03 19:00:25,782 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\111111', 'd:\\OneDrive\\桌面\\111111\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\111111', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\111111\\src']
2025-07-03 19:00:25,782 - INFO - RecommendationService Loading successful
2025-07-03 19:00:25,782 - INFO - reset_books exist: True
2025-07-03 19:00:25,782 - INFO - ==================================================
2025-07-03 19:00:25,782 - INFO - Successfully imported LibraryApp
2025-07-03 19:00:25,782 - INFO - LibraryApp Instance created successfully
2025-07-03 19:00:25,782 - INFO - The method to display the login interface has been called
2025-07-03 19:23:10,312 - INFO - ==================================================
2025-07-03 19:23:10,313 - INFO - Start environment debugging information:
2025-07-03 19:23:10,313 - INFO - current working directory: d:\OneDrive\桌面\111111
2025-07-03 19:23:10,313 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\111111', 'd:\\OneDrive\\桌面\\111111\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\111111', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\111111\\src']
2025-07-03 19:23:10,314 - INFO - RecommendationService Loading successful
2025-07-03 19:23:10,314 - INFO - reset_books exist: True
2025-07-03 19:23:10,314 - INFO - ==================================================
2025-07-03 19:23:10,314 - INFO - Successfully imported LibraryApp
2025-07-03 19:23:10,314 - INFO - LibraryApp Instance created successfully
2025-07-03 19:23:10,314 - INFO - The method to display the login interface has been called
2025-07-03 19:33:43,797 - INFO - ==================================================
2025-07-03 19:33:43,798 - INFO - Start environment debugging information:
2025-07-03 19:33:43,798 - INFO - current working directory: d:\OneDrive\桌面\111111
2025-07-03 19:33:43,798 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\111111', 'd:\\OneDrive\\桌面\\111111\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\111111', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\111111\\src']
2025-07-03 19:33:43,799 - INFO - RecommendationService Loading successful
2025-07-03 19:33:43,799 - INFO - reset_books exist: True
2025-07-03 19:33:43,799 - INFO - ==================================================
2025-07-03 19:33:43,799 - INFO - Successfully imported LibraryApp
2025-07-03 19:33:43,799 - INFO - LibraryApp Instance created successfully
2025-07-03 19:33:43,799 - INFO - The method to display the login interface has been called
2025-07-04 09:15:23,744 - INFO - ==================================================
2025-07-04 09:15:23,755 - INFO - Start environment debugging information:
2025-07-04 09:15:23,755 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:15:23,755 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:15:23,756 - INFO - RecommendationService Loading successful
2025-07-04 09:15:23,756 - INFO - reset_books exist: True
2025-07-04 09:15:23,756 - INFO - ==================================================
2025-07-04 09:15:23,756 - INFO - Successfully imported LibraryApp
2025-07-04 09:15:23,756 - CRITICAL - Application startup failed: 模拟导入错误
2025-07-04 09:15:23,765 - INFO - ==================================================
2025-07-04 09:15:23,765 - INFO - Start environment debugging information:
2025-07-04 09:15:23,765 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:15:23,766 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:15:23,766 - INFO - RecommendationService Loading successful
2025-07-04 09:15:23,766 - INFO - reset_books exist: True
2025-07-04 09:15:23,766 - INFO - ==================================================
2025-07-04 09:15:23,766 - INFO - Successfully imported LibraryApp
2025-07-04 09:15:23,767 - INFO - LibraryApp Instance created successfully
2025-07-04 09:15:23,767 - INFO - The method to display the login interface has been called
2025-07-04 09:20:25,783 - INFO - ==================================================
2025-07-04 09:20:25,783 - INFO - Start environment debugging information:
2025-07-04 09:20:25,783 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:20:25,784 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:20:25,784 - ERROR - Module loading failed: module services.RecommendationService not in sys.modules
2025-07-04 09:20:25,784 - INFO - ==================================================
2025-07-04 09:20:25,784 - INFO - Successfully imported LibraryApp
2025-07-04 09:20:25,784 - CRITICAL - Application startup failed: 模拟导入错误
2025-07-04 09:20:25,794 - INFO - ==================================================
2025-07-04 09:20:25,794 - INFO - Start environment debugging information:
2025-07-04 09:20:25,794 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:20:25,794 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:20:25,794 - ERROR - Module loading failed: module services.RecommendationService not in sys.modules
2025-07-04 09:20:25,795 - INFO - ==================================================
2025-07-04 09:20:25,795 - INFO - Successfully imported LibraryApp
2025-07-04 09:20:25,795 - INFO - LibraryApp Instance created successfully
2025-07-04 09:20:25,795 - INFO - The method to display the login interface has been called
2025-07-04 09:20:39,335 - INFO - ==================================================
2025-07-04 09:20:39,336 - INFO - Start environment debugging information:
2025-07-04 09:20:39,336 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:20:39,336 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:20:39,336 - ERROR - Module loading failed: module services.RecommendationService not in sys.modules
2025-07-04 09:20:39,336 - INFO - ==================================================
2025-07-04 09:20:39,336 - INFO - Successfully imported LibraryApp
2025-07-04 09:20:39,336 - CRITICAL - Application startup failed: 模拟导入错误
2025-07-04 09:20:39,345 - INFO - ==================================================
2025-07-04 09:20:39,345 - INFO - Start environment debugging information:
2025-07-04 09:20:39,345 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:20:39,345 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:20:39,345 - ERROR - Module loading failed: module services.RecommendationService not in sys.modules
2025-07-04 09:20:39,345 - INFO - ==================================================
2025-07-04 09:20:39,345 - INFO - Successfully imported LibraryApp
2025-07-04 09:20:39,346 - INFO - LibraryApp Instance created successfully
2025-07-04 09:20:39,346 - INFO - The method to display the login interface has been called
2025-07-04 09:22:03,500 - INFO - ==================================================
2025-07-04 09:22:03,501 - INFO - Start environment debugging information:
2025-07-04 09:22:03,501 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:22:03,501 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:22:03,501 - INFO - RecommendationService Loading successful
2025-07-04 09:22:03,501 - INFO - reset_books exist: True
2025-07-04 09:22:03,501 - INFO - ==================================================
2025-07-04 09:22:03,501 - INFO - Successfully imported LibraryApp
2025-07-04 09:22:03,501 - INFO - LibraryApp Instance created successfully
2025-07-04 09:22:03,502 - INFO - The method to display the login interface has been called
2025-07-04 09:22:11,978 - INFO - ==================================================
2025-07-04 09:22:11,979 - INFO - Start environment debugging information:
2025-07-04 09:22:11,979 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:22:11,979 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:22:11,979 - INFO - RecommendationService Loading successful
2025-07-04 09:22:11,979 - INFO - reset_books exist: True
2025-07-04 09:22:11,980 - INFO - ==================================================
2025-07-04 09:22:11,980 - INFO - Successfully imported LibraryApp
2025-07-04 09:22:11,980 - INFO - LibraryApp Instance created successfully
2025-07-04 09:22:11,980 - INFO - The method to display the login interface has been called
2025-07-04 09:36:51,874 - INFO - ==================================================
2025-07-04 09:36:51,875 - INFO - Start environment debugging information:
2025-07-04 09:36:51,875 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:36:51,875 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:36:51,876 - INFO - RecommendationService Loading successful
2025-07-04 09:36:51,876 - INFO - reset_books exist: True
2025-07-04 09:36:51,876 - INFO - ==================================================
2025-07-04 09:36:51,876 - INFO - Successfully imported LibraryApp
2025-07-04 09:36:51,876 - INFO - LibraryApp Instance created successfully
2025-07-04 09:36:51,877 - INFO - The method to display the login interface has been called
2025-07-04 09:38:20,935 - INFO - ==================================================
2025-07-04 09:38:20,935 - INFO - Start environment debugging information:
2025-07-04 09:38:20,935 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:38:20,935 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:38:20,936 - INFO - RecommendationService Loading successful
2025-07-04 09:38:20,936 - INFO - reset_books exist: True
2025-07-04 09:38:20,936 - INFO - ==================================================
2025-07-04 09:38:20,936 - INFO - Successfully imported LibraryApp
2025-07-04 09:38:20,936 - INFO - LibraryApp Instance created successfully
2025-07-04 09:38:20,936 - INFO - The method to display the login interface has been called
2025-07-04 09:38:28,319 - INFO - ==================================================
2025-07-04 09:38:28,319 - INFO - Start environment debugging information:
2025-07-04 09:38:28,320 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 09:38:28,320 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 09:38:28,320 - INFO - RecommendationService Loading successful
2025-07-04 09:38:28,321 - INFO - reset_books exist: True
2025-07-04 09:38:28,321 - INFO - ==================================================
2025-07-04 09:38:28,321 - INFO - Successfully imported LibraryApp
2025-07-04 09:38:28,321 - INFO - LibraryApp Instance created successfully
2025-07-04 09:38:28,321 - INFO - The method to display the login interface has been called
2025-07-04 10:28:34,909 - INFO - ==================================================
2025-07-04 10:28:34,909 - INFO - Start environment debugging information:
2025-07-04 10:28:34,909 - INFO - current working directory: d:\OneDrive\桌面\Library Management System  3.3
2025-07-04 10:28:34,909 - INFO - Python Path: ['d:\\OneDrive\\桌面', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\tests', '.', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'd:\\OneDrive\\桌面\\Library Management System  3.3', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\python313.zip', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\DLLs', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313', 'C:\\Users\\hry2576\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\unittestadapter', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files', 'c:\\Users\\hry2576\\.vscode\\extensions\\ms-python.python-2025.8.0-win32-x64\\python_files\\lib\\python', 'd:\\OneDrive\\桌面\\Library Management System  3.3\\src']
2025-07-04 10:28:34,910 - INFO - RecommendationService Loading successful
2025-07-04 10:28:34,910 - INFO - reset_books exist: True
2025-07-04 10:28:34,910 - INFO - ==================================================
2025-07-04 10:28:34,910 - INFO - Successfully imported LibraryApp
2025-07-04 10:28:34,910 - INFO - LibraryApp Instance created successfully
2025-07-04 10:28:34,910 - INFO - The method to display the login interface has been called
